# Generated by Django 4.0.4 on 2022-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField(max_length=5000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
