# Generated by Django 4.0.3 on 2022-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('panNo', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('completed', models.BooleanField()),
                ('timeStamp', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
